name: Jimmy Love
favicon: null
layout_spectrum: 0.688830477418378
typography_spectrum: 0.05498500447720289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7944041616283357
  lightness: 0.14273261767812073
  saturation: 0.3398278809618205
  rhythmicContrast: 0.4469994904939085
purpose: []
